# Generated by Django 5.0.2 on 2024-02-14 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_enquiry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
